### ISSUE TITLE
FR: Create hotspot from client/server

### ISSUE THREAD

**Issue by roshin8** [milesial/xfinity-refresh#1]
I was wondering if it's possible to have an option to create a Wi-Fi hotspot from the server (raspberry pi) or the client (laptop) so that devices that don't have root access (android/TV) to change the mac can connect to that hotspot?  
P.S: Great program!

**Comment by milesial** [comment]
Hi, thanks ;)

So I thought about this, and if you want almost no internet interruption you would need to implement the hotspot on the client device.

If you already managed to make the app work with a client/server, try looking up how to share internet from one interface via a hotspot for your client OS, it should work ( Ubuntu: https://askubuntu.com/questions/318973/how-do-i-create-a-wifi-hotspot-sharing-wireless-internet-connection-single-adap )

I don't think I would be able to add it as an option in this app as this can be quite specific to each OS and setup.

**Comment by roshin8** [comment]
That makes sense. Thanks! :)
